server:
  port: 8080

oauth2:
  redirect-uri: http://my-portal:8080/login/oauth2/code/portal-client
  issuer-uri: http://my-portal:8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://my-auth:8080
  datasource:
    url: jdbc:postgresql://niq-dev.com:5432/my_auth
    driver-class-name: org.postgresql.Driver
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/prod
    