spring:
  application:
    name: my-auth
  security:
    user:
      name: admin
      password: password
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
          jwk-set-uri: http://localhost:8081/oauth2/jwks

server:
  port: 8081

logging:
  level:
    '[org.hibernate.SQL]': debug  # 開啟 Hibernate SQL 輸出（選擇性）
    '[org.hibernate.type.descriptor.sql.BasicBinder]': trace  # 顯示 Hibernate 綁定變數
    '[org.springframework.security]': debug
    '[org.springframework.web]': debug
