INSERT INTO public.oauth2_registered_client (
	id, 
	client_id, 
	client_id_issued_at, 
	client_secret, 
	client_secret_expires_at, 
	client_name, 
	client_authentication_methods, 
	authorization_grant_types, 
	redirect_uris, 
	post_logout_redirect_uris, 
	scopes, 
	client_settings, 
	token_settings
) VALUES (
	uuid_generate_v4(),
	'portal-client', 
	NOW(), 
	'{bcrypt}$2a$10$PamQcqOkgZr7p7oay/eaOubTqongxTK2t1YiA/FIr2wpO4BlldFlG', 
	NULL, 
	'Portal Client', 
	'client_secret_basic', 
	'refresh_token,client_credentials,authorization_code', 
	'http://localhost:8080/login/oauth2/code/portal-client', 
	'', 
	'read,openid', 
	'{
		"@class":"java.util.Collections$UnmodifiableMap",
		"settings.client.require-proof-key":false,
		"settings.client.require-authorization-consent":true
	}', 
	'{
		"@class":"java.util.Collections$UnmodifiableMap",
		"settings.token.reuse-refresh-tokens":false,
		"settings.token.x509-certificate-bound-access-tokens":false,
		"settings.token.id-token-signature-algorithm":["org.springframework.security.oauth2.jose.jws.SignatureAlgorithm","RS256"],
		"settings.token.access-token-time-to-live":["java.time.Duration",1800.000000000],
		"settings.token.access-token-format":{
			"@class":"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat",
			"value":"self-contained"
		},
		"settings.token.refresh-token-time-to-live":["java.time.Duration",28800.000000000],
		"settings.token.authorization-code-time-to-live":["java.time.Duration",300.000000000],
		"settings.token.device-code-time-to-live":["java.time.Duration",300.000000000]
	}'
);
